package seleniumFrameworkDesign.stepDefinations;

import java.io.IOException;

import org.testng.Assert;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import seleniumFrameworkDesign.pageObjects.CartPage;
import seleniumFrameworkDesign.pageObjects.LoginPage;
import seleniumFrameworkDesign.pageObjects.OrderConfirmationPage;
import seleniumFrameworkDesign.pageObjects.OrderPaymentPage;
import seleniumFrameworkDesign.pageObjects.ProductCatalogue;
import seleniumFrameworkDesign.testComponents.BaseTest;

public class StepDefinationImplematntation extends BaseTest {
	// for using cucumber download cucumber-java, cucumber-testng from maven,
	// also download cucumber plugin from eclipse marketplace
	// all structure of step defiation file can be auto generated by using tidy
	// gherkin chrome plugin
	LoginPage lp;
	ProductCatalogue pc;
	OrderPaymentPage opp;
	CartPage cp;
	OrderConfirmationPage ocp;

	@Given("I landed on ecommerce page")
	public void I_landed_on_ecommerce_page() throws IOException {
		lp = launchApplication();
		System.out.println("I_landed_on_ecommerce_page");
	}

	// (.+) is regEx it implies that value will come dynamically
	// for using regEx string shuould be covered with ^ and $ eg. -> ^String$
	@Given("^I logged in with user email (.+) and password (.+)$")
	public void logged_in_username_password(String username, String password) {
		pc = lp.loginToApplication(username, password);
		System.out.println("logged_in_username_password");
	}

	@When("^I add product (.+) to cart$")
	public void I_product_to_cart(String desired_product_name) throws InterruptedException {
		pc.addProductToCart(desired_product_name);
		System.out.println("I_product_to_cart");
	}

	@When("^checkout (.+) and submit order$")
	public void checkout_desired_product_submit_order(String desired_product_name) {
		CartPage cp = pc.goToCartPage();
		// verify whether product added in cart
		Boolean is_cart_item_present = cp.verifyProductAddedInCart(desired_product_name);
		// Assertions should be written in test page only and not in page object class
		Assert.assertTrue(is_cart_item_present, desired_product_name + "does not present in cart");
		// proceed for checkout(order payment page will come)
		opp = cp.checkOut();

		// enter desired country
		String desired_country = "India";
		opp.selectCountry(desired_country, "ind");
		// place order
		ocp = opp.placeOrder();

		System.out.println("checkout_desired_product_submit_order");
	}

	@Then("{string} message is displayed on the confirmation page")
	public void message_displayed_confirmation_page(String confirmation_message) throws InterruptedException {
		Assert.assertEquals(ocp.get_confirmation_message(), confirmation_message);
		System.out.println("confirmation_page");
		quitApplication();
	}

	@Then("{string} message is displayed")
	public void error_message_is_displayed(String strArg1) throws Throwable {
		Assert.assertEquals(lp.getErrorMessage(), strArg1);
		quitApplication();
	}

}
